module.exports = {
  ['User-post-400--bio-missing']: {
    code: '400',
    detail: 'You must provide a `bio` string property',
    id: 'User-post-400--bio-missing',
    links: { about: '' },
    source: { pointer: '' },
    status: '400 Bad Request',
    title: 'Missing Attribute',
  },
  ['User-post-400--email-missing']: {
    code: '400',
    detail: 'You must provide a `email` string property',
    id: 'User-put-400--email-missing',
    links: { about: '' },
    source: { pointer: '' },
    status: '400 Bad Request',
    title: 'Missing Attribute',
  },
  ['User-post-400--firstName-missing']: {
    code: '400',
    detail: 'You must provide a `firstName` string property',
    id: 'User-post-400--firstName-missing',
    links: { about: '' },
    source: { pointer: '' },
    status: '400 Bad Request',
    title: 'Missing Attribute',
  },
  ['User-post-400--lastName-missing']: {
    code: '400',
    detail: 'You must provide a `lastName` string property',
    id: 'User-post-400--lastName-missing',
    links: { about: '' },
    source: { pointer: '' },
    status: '400 Bad Request',
    title: 'Missing Attribute',
  },
  ['User-post-400--imageURL-missing']: {
    code: '400',
    detail: 'You must provide a `imageURL` string property',
    id: 'User-post-400--imageURL-missing',
    links: { about: '' },
    source: { pointer: '' },
    status: '400 Bad Request',
    title: 'Missing Attribute',
  },
};
